from collections import deque
from pathlib import Path
import csv
import json
from datetime import datetime
import random

import numpy as np
import torch

from game_logic_Ai import P1, P2, TOTAL_ACTIONS, NUM_MOVE_ACTIONS
from model import PolicyValueNet, AlphaZeroTrainer
from mcts import MCTS


SCRIPT_DIR = Path(__file__).resolve().parent
PLOTS_DIR = SCRIPT_DIR.parent / "plots"
PLOTS_DIR.mkdir(exist_ok=True)
MODEL_DIR = SCRIPT_DIR.parent / "model"
MODEL_DIR.mkdir(exist_ok=True)
METRICS_DIR = SCRIPT_DIR.parent / "training_metrics"
METRICS_DIR.mkdir(exist_ok=True)
RUN_TIMESTAMP = datetime.now().strftime("%Y%m%d_%H%M%S")

MAX_MEMORY = 100000
MAX_STEPS_PER_GAME = 400
ALPHAZERO_BATCH_SIZE = 64


class AlphaZeroExample:
    """
    One training example generated by self-play.

    Fields:
    - state: canonical board tensor from the acting player's perspective
    - target_policy: distribution over the 144 action slots
    - player: the real player id that owned this state
    - target_value: final result from that player's perspective
    """

    def __init__(self, state, target_policy, player, target_value=None):
        self.state = state
        self.target_policy = target_policy
        self.player = player
        self.target_value = target_value


class AlphaZeroSelfPlayAgent:
    """
    Main learning agent for the MCTS + policy-value pipeline.

    This agent owns:
    - the policy-value network
    - the AlphaZero trainer
    - the replay buffer of (state, pi, z) examples
    """

    def __init__(self, lr=0.001, temperature=1.0):
        self.n_games = 0
        self.temperature = temperature
        self.model = PolicyValueNet(
            input_channels=6,
            board_size=9,
            num_actions=TOTAL_ACTIONS,
        )
        self.trainer = AlphaZeroTrainer(self.model, lr=lr)
        self.examples = deque(maxlen=MAX_MEMORY)
        self.current_game_examples = []

    def start_new_game(self):
        self.current_game_examples = []

    def predict(self, state):
        return self.model.predict(state)

    def mask_and_normalize_policy(self, policy, valid_actions):
        """
        Zero-out illegal actions and renormalize over the legal ones.
        """
        masked_policy = np.zeros(TOTAL_ACTIONS, dtype=np.float32)
        masked_policy[valid_actions] = policy[valid_actions]

        total_prob = float(masked_policy.sum())
        if total_prob <= 0:
            masked_policy[valid_actions] = 1.0 / len(valid_actions)
            return masked_policy

        masked_policy /= total_prob
        return masked_policy

    def select_action_from_policy(self, policy, valid_actions, temperature=None):
        """
        Sample one action directly from a policy distribution.

        This helper is useful both for tests and for simple experiments,
        even though the main training loop usually samples from MCTS visit counts.
        """
        if temperature is None:
            temperature = self.temperature

        masked_policy = self.mask_and_normalize_policy(policy, valid_actions)

        if temperature <= 1e-8:
            return int(np.argmax(masked_policy))

        tempered_policy = masked_policy ** (1.0 / temperature)
        tempered_policy /= tempered_policy.sum()
        return int(np.random.choice(np.arange(TOTAL_ACTIONS), p=tempered_policy))

    def record_policy_example(self, state, target_policy, player):
        self.current_game_examples.append(
            AlphaZeroExample(
                state=np.array(state, dtype=np.float32, copy=True),
                target_policy=np.array(target_policy, dtype=np.float32, copy=True),
                player=player,
                target_value=None,
            )
        )

    def finalize_game_examples(self, winner):
        """
        Fill z for every stored position once the game ends.
        """
        finalized_examples = []

        for example in self.current_game_examples:
            if winner is None:
                example.target_value = 0.0
            else:
                example.target_value = 1.0 if example.player == winner else -1.0

            finalized_examples.append(example)
            self.examples.append(example)

        self.current_game_examples = []
        self.n_games += 1
        return finalized_examples

    def train_from_examples(self, batch_size=ALPHAZERO_BATCH_SIZE):
        if not self.examples:
            return None

        if len(self.examples) > batch_size:
            mini_batch = random.sample(self.examples, batch_size)
        else:
            mini_batch = list(self.examples)

        states = np.array([example.state for example in mini_batch], dtype=np.float32)
        target_policies = np.array(
            [example.target_policy for example in mini_batch], dtype=np.float32
        )
        target_values = np.array(
            [example.target_value for example in mini_batch], dtype=np.float32
        )

        return self.trainer.train_step(states, target_policies, target_values)

    def save_checkpoint(self, file_name, extra_metadata=None):
        checkpoint = {
            "model_state_dict": self.model.state_dict(),
            "n_games": self.n_games,
            "temperature": self.temperature,
        }

        if extra_metadata is not None:
            checkpoint["metadata"] = extra_metadata

        torch.save(checkpoint, MODEL_DIR / file_name)


def train_alphazero_self_play(
    env,
    agent,
    plotter,
    ui=None,
    num_games=100,
    num_simulations=50,
    c_puct=1.5,
    root_dirichlet_alpha=0.3,
    root_dirichlet_epsilon=0.25,
    temperature=1.0,
    temperature_drop_step=10,
):
    """
    Full AlphaZero-style self-play loop.

    Per move:
    1. run MCTS from the current position
    2. convert root visit counts into target policy pi
    3. sample an action from pi
    4. store (state, pi, player)

    At the end of the game:
    5. assign final z values
    6. train the policy-value network on the collected examples
    """
    record_value_loss = float("inf")
    stats = {
        "steps": [],
        "p1_rewards": [],
        "p2_rewards": [],
        "walls": [],
        "p1_wins": [],
        "p2_wins": [],
        "exploration_rate_p1": [],
        "exploration_rate_p2": [],
        "invalid_moves": [],
        "shared_scores": [],
        "timeouts": [],
        "policy_loss": [],
        "value_loss": [],
        "total_loss": [],
        "examples_per_game": [],
    }

    metrics_csv_path = METRICS_DIR / f"alphazero_self_play_metrics_{RUN_TIMESTAMP}.csv"
    metrics_json_path = METRICS_DIR / f"alphazero_self_play_summary_{RUN_TIMESTAMP}.json"

    for game_num in range(num_games):
        env.reset()
        agent.start_new_game()
        done = False
        step_count = 0
        wall_count = 0
        invalid_count = 0
        root_temperature = temperature

        print(
            f"\n================ Starting AlphaZero Self-Play Game {game_num + 1} ================"
        )

        if ui is not None:
            ui.new_game()

        while not done and step_count < MAX_STEPS_PER_GAME:
            current_player = env.get_current_player()
            canonical_state = env.get_canonical_state(current_player)

            search = MCTS(
                agent=agent,
                num_simulations=num_simulations,
                c_puct=c_puct,
                dirichlet_alpha=root_dirichlet_alpha,
                dirichlet_epsilon=root_dirichlet_epsilon,
                add_dirichlet_noise=True,
            )
            root = search.run(env)

            # Early in the game we keep more exploration, later we collapse
            # toward the most visited move.
            root_temperature = (
                temperature if step_count < temperature_drop_step else 0.0
            )
            target_policy = search.get_action_probs(root, temperature=root_temperature)

            agent.record_policy_example(
                state=canonical_state,
                target_policy=target_policy,
                player=current_player,
            )

            action = search.select_action(root, temperature=root_temperature)
            _, done, info = env.apply_action(action)

            if info.get("invalid", False):
                invalid_count += 1
            elif action >= NUM_MOVE_ACTIONS:
                wall_count += 1

            step_count += 1

            if ui is not None:
                ui.render(game_num=game_num + 1, step=step_count)

        timeout_reached = step_count >= MAX_STEPS_PER_GAME and not env.is_terminal()
        winner = None if timeout_reached else env.get_winner()
        finalized_examples = agent.finalize_game_examples(winner=winner)
        train_info = agent.train_from_examples(batch_size=ALPHAZERO_BATCH_SIZE)

        p1_outcome = 0.0 if winner is None else (1.0 if winner == P1 else -1.0)
        p2_outcome = -p1_outcome
        shared_score = p1_outcome + p2_outcome

        if train_info is None:
            train_info = {
                "total_loss": 0.0,
                "policy_loss": 0.0,
                "value_loss": 0.0,
            }

        if train_info["value_loss"] < record_value_loss:
            record_value_loss = train_info["value_loss"]
            agent.save_checkpoint(
                "PolicyValueNet_alphazero_best_value_loss.pth",
                extra_metadata={
                    "game_num": game_num + 1,
                    "value_loss": record_value_loss,
                    "policy_loss": train_info["policy_loss"],
                    "total_loss": train_info["total_loss"],
                },
            )

        agent.save_checkpoint(
            "PolicyValueNet_alphazero_latest.pth",
            extra_metadata={
                "game_num": game_num + 1,
                "value_loss": train_info["value_loss"],
                "policy_loss": train_info["policy_loss"],
                "total_loss": train_info["total_loss"],
                "examples_in_buffer": len(agent.examples),
            },
        )

        stats["steps"].append(step_count)
        stats["p1_rewards"].append(p1_outcome)
        stats["p2_rewards"].append(p2_outcome)
        stats["walls"].append(wall_count)
        stats["p1_wins"].append(1 if winner == P1 else 0)
        stats["p2_wins"].append(1 if winner == P2 else 0)
        stats["invalid_moves"].append(invalid_count)
        stats["shared_scores"].append(shared_score)
        stats["timeouts"].append(1 if timeout_reached else 0)
        # Reuse the old plot layout: here "exploration" means root temperature.
        stats["exploration_rate_p1"].append(root_temperature)
        stats["exploration_rate_p2"].append(root_temperature)
        stats["policy_loss"].append(train_info["policy_loss"])
        stats["value_loss"].append(train_info["value_loss"])
        stats["total_loss"].append(train_info["total_loss"])
        stats["examples_per_game"].append(len(finalized_examples))
        if plotter is not None:
            plotter.update(stats)

        _append_metrics_row(
            metrics_csv_path,
            {
                "game": game_num + 1,
                "steps": step_count,
                "winner": winner,
                "timeout": int(timeout_reached),
                "walls": wall_count,
                "invalid_moves": invalid_count,
                "examples_generated": len(finalized_examples),
                "replay_size": len(agent.examples),
                "policy_loss": round(train_info["policy_loss"], 6),
                "value_loss": round(train_info["value_loss"], 6),
                "total_loss": round(train_info["total_loss"], 6),
                "root_temperature": root_temperature,
                "num_simulations": num_simulations,
            },
        )

        _write_alphazero_metrics_summary(
            metrics_json_path,
            stats,
            latest_game=game_num + 1,
            latest_winner=winner,
            replay_size=len(agent.examples),
        )

        print(
            f"\nGame {game_num + 1} | "
            f"Winner: {winner} | "
            f"Steps: {step_count} | "
            f"Examples: {len(finalized_examples)} | "
            f"Replay: {len(agent.examples)} | "
            f"Policy Loss: {train_info['policy_loss']:.4f} | "
            f"Value Loss: {train_info['value_loss']:.4f} | "
            f"Total Loss: {train_info['total_loss']:.4f}"
        )

    if plotter is not None:
        plotter.fig.savefig(
            str(PLOTS_DIR / "training_alphazero_self_play.png"),
            dpi=300,
            bbox_inches="tight",
        )


def _append_metrics_row(csv_path, row):
    fieldnames = list(row.keys())
    write_header = not csv_path.exists()

    with csv_path.open("a", newline="", encoding="utf-8") as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
        if write_header:
            writer.writeheader()
        writer.writerow(row)


def _write_alphazero_metrics_summary(
    metrics_json_path, stats, latest_game, latest_winner, replay_size
):
    summary = {
        "latest_game": latest_game,
        "latest_winner": latest_winner,
        "replay_size": replay_size,
        "total_p1_wins": int(sum(stats["p1_wins"])),
        "total_p2_wins": int(sum(stats["p2_wins"])),
        "timeouts": int(sum(stats["timeouts"])),
        "avg_steps": float(np.mean(stats["steps"])) if stats["steps"] else 0.0,
        "avg_policy_loss": (
            float(np.mean(stats["policy_loss"])) if stats["policy_loss"] else 0.0
        ),
        "avg_value_loss": (
            float(np.mean(stats["value_loss"])) if stats["value_loss"] else 0.0
        ),
        "avg_total_loss": (
            float(np.mean(stats["total_loss"])) if stats["total_loss"] else 0.0
        ),
        "avg_examples_per_game": (
            float(np.mean(stats["examples_per_game"]))
            if stats["examples_per_game"]
            else 0.0
        ),
    }

    with metrics_json_path.open("w", encoding="utf-8") as metrics_file:
        json.dump(summary, metrics_file, indent=2)
