from collections import deque
from pathlib import Path
import random

import numpy as np
import torch

from game_logic_Ai import (
    DEFAULT_GRID_SIZE,
    DEFAULT_MAX_WALLS,
    total_actions_for_grid,
)
from model import PolicyValueNet, AlphaZeroTrainer


SCRIPT_DIR = Path(__file__).resolve().parent
MODEL_DIR = SCRIPT_DIR.parent / "model"
MODEL_DIR.mkdir(exist_ok=True)

MAX_MEMORY = 100000
ALPHAZERO_BATCH_SIZE = 64


class AlphaZeroExample:
    """
    One training example generated by self-play.

    Fields:
    - state: canonical board tensor from the acting player's perspective
    - target_policy: distribution over the configured action slots
    - player: the real player id that owned this state
    - target_value: final result from that player's perspective
    """

    def __init__(self, state, target_policy, player, target_value=None):
        self.state = state
        self.target_policy = target_policy
        self.player = player
        self.target_value = target_value


class AlphaZeroSelfPlayAgent:
    """
    Main learning agent for the MCTS + policy-value pipeline.

    This agent owns:
    - the policy-value network
    - the AlphaZero trainer
    - the replay buffer of (state, pi, z) examples
    """

    def __init__(
        self,
        lr=0.001,
        temperature=1.0,
        board_size=DEFAULT_GRID_SIZE,
        max_walls=DEFAULT_MAX_WALLS,
        num_actions=None,
        num_filters=64,
    ):
        self.n_games = 0
        self.temperature = temperature
        self.board_size = board_size
        self.max_walls = max_walls
        self.num_filters = num_filters
        self.num_actions = (
            total_actions_for_grid(board_size) if num_actions is None else num_actions
        )
        self.model = PolicyValueNet(
            input_channels=6,
            board_size=self.board_size,
            num_actions=self.num_actions,
            num_filters=self.num_filters,
        )
        self.trainer = AlphaZeroTrainer(self.model, lr=lr)
        self.examples = deque(maxlen=MAX_MEMORY)
        self.current_game_examples = []

    def start_new_game(self):
        self.current_game_examples = []

    def predict(self, state):
        return self.model.predict(state)

    def predict_batch(self, states):
        return self.model.predict_batch(states)

    def mask_and_normalize_policy(self, policy, valid_actions):
        """
        Zero-out illegal actions and renormalize over the legal ones.
        """
        masked_policy = np.zeros(self.num_actions, dtype=np.float32)
        masked_policy[valid_actions] = policy[valid_actions]

        total_prob = float(masked_policy.sum())
        if total_prob <= 0:
            masked_policy[valid_actions] = 1.0 / len(valid_actions)
            return masked_policy

        masked_policy /= total_prob
        return masked_policy

    def select_action_from_policy(self, policy, valid_actions, temperature=None):
        """
        Sample one action directly from a policy distribution.

        This helper is useful both for tests and for simple experiments,
        even though the main training loop usually samples from MCTS visit counts.
        """
        if temperature is None:
            temperature = self.temperature

        masked_policy = self.mask_and_normalize_policy(policy, valid_actions)

        if temperature <= 1e-8:
            return int(np.argmax(masked_policy))

        tempered_policy = masked_policy ** (1.0 / temperature)
        tempered_policy /= tempered_policy.sum()
        return int(np.random.choice(np.arange(self.num_actions), p=tempered_policy))

    def record_policy_example(self, state, target_policy, player):
        self.current_game_examples.append(
            AlphaZeroExample(
                state=np.array(state, dtype=np.float32, copy=True),
                target_policy=np.array(target_policy, dtype=np.float32, copy=True),
                player=player,
                target_value=None,
            )
        )

    def finalize_game_examples(self, winner, outcome_value=1.0):
        """
        Fill z for every stored position once the game ends.
        """
        finalized_examples = []

        for example in self.current_game_examples:
            if winner is None:
                example.target_value = 0.0
            else:
                # Real terminal wins use the full +/-1 target. Timeout
                # adjudications can pass a smaller value, because "closer to
                # goal" is useful but less certain than an actual win.
                example.target_value = (
                    outcome_value if example.player == winner else -outcome_value
                )

            finalized_examples.append(example)
            self.examples.append(example)

        self.current_game_examples = []
        self.n_games += 1
        return finalized_examples

    def train_from_examples(self, batch_size=ALPHAZERO_BATCH_SIZE):
        if not self.examples:
            return None

        if len(self.examples) > batch_size:
            mini_batch = random.sample(self.examples, batch_size)
        else:
            mini_batch = list(self.examples)

        states = np.array([example.state for example in mini_batch], dtype=np.float32)
        target_policies = np.array(
            [example.target_policy for example in mini_batch], dtype=np.float32
        )
        target_values = np.array(
            [example.target_value for example in mini_batch], dtype=np.float32
        )

        return self.trainer.train_step(states, target_policies, target_values)

    def save_checkpoint(self, file_name, extra_metadata=None):
        checkpoint = {
            "model_state_dict": self.model.state_dict(),
            "n_games": self.n_games,
            "temperature": self.temperature,
            "board_size": self.board_size,
            "max_walls": self.max_walls,
            "num_actions": self.num_actions,
            "num_filters": self.num_filters,
        }

        if extra_metadata is not None:
            checkpoint["metadata"] = extra_metadata

        torch.save(checkpoint, MODEL_DIR / file_name)
